[profile.default]
# These are defualt config
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
verbosity = 3 # this makes -vv default

[fmt]
line_length = 100
tab_width = 4

remappings = [
  "@fm/=./src/"
]

