[profile.default]
# These are defualt config
src = "src"
out = "out"
libs = ["lib"]

# Modified
verbosity=3 #this make -vv default. For instance, forge test -vv will be default

[fmt]
line_length = 100
tab_width = 4

